title: Spacy Algo config for Acharya
owner: Sanskriti Modi
author: SM
train:
        cmd: python3 train.py
        type: cmd
        input: data/gu_train.iob
        output: stdout
eval:
        cmd: python3 evaluate_model.py
        type: cmd
        input: data/gu_eval.iob
        output: "tcp::5566"
