title: Spacy Algo config for Acharya
owner: Sanskriti Modi
author: SM
train:
        cmd: usr/bin/sh train.sh
        type: cmd
        input: data/gu_train.iob
        output: stdout
eval:
        cmd: python3 evaluate.py
        type: cmd
        input: data/gu_eval.iob
        output: stdout
